- title: "Management of actuator dynamics in a multiple actuator hard disk drive with an unequal number of heads on the two outer arms of each actuator"
  authors:
    - Manoj Keshavan
    - Siddhesh Vivek Sakhalkar
    - Hitoshi Shindo
  publisher: "US Patent 11664047B2"
  date: "2023-05-30"
  link: "https://patents.google.com/patent/US11664047B2/en"
